### ISSUE TITLE
feat: export link or markdown containing original code

### ISSUE THREAD

**Issue by jimthedev** [octref/polacode#10]
This is so great, one thing that would be super useful is if it could also generate a link or a markdown file that would take you to a place where you could copy/paste the original code and even edit it. Keeping images up to date in documentation sucks but this could be a really nice way to offer the best of both worlds.

**Comment by octref** [comment]
All I'll do it #16. When that becomes available you can write your own gulp plugin and markdown converter plugin to do what you want.
