### ISSUE TITLE
vscode.previewHTML is deprecated please fix

### ISSUE THREAD

**Issue by PRASHANTPR7** [octref/polacode#100]
when i open polacode it say this->
Extension 'pnp.polacode' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by superheri** [comment]
This is so much deprecated that it's not working at all in VS Code Insiders.

**Comment by pavanjadhaw** [comment]
See https://github.com/octref/polacode/issues/103#issuecomment-485533758

**Comment by Toxblh** [comment]
I fixed marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork
