### ISSUE TITLE
Polacode 'vscode.previewHtml' deprecated, please fix

### ISSUE THREAD

**Issue by Mebru** [octref/polacode#101]
![Screenshot 2019-03-20 at 08 59 04](https://user-images.githubusercontent.com/48748555/54665337-7c074080-4aef-11e9-83d6-07a53f47b1fa.png)

**Comment by xasx** [comment]
There's already a branch which exists since about a year now.

Does it work? How can I make use of it or test?

**Comment by xasx** [comment]
Duplicates #100

**Comment by xasx** [comment]
Promising fork: https://github.com/danielphan2003/polacode

**Comment by CodefulDom** [comment]
@xasx I am getting the same error as mentioned from the main repo, am I missing something?

**Comment by CodefulDom** [comment]
I take that back @xasx works fine from the fork! **Great Find!!**

**Comment by xasx** [comment]
I am not able to simply build the extension from the fork. It just does not load and throws errors without meaningful messages.

Since I am a novice in VSCode extensions, electron and Node development altogether, I can not guarantee that I find some time to get this fixed. 

Maybe some experienced dev is out there :eyes:

**Comment by VivekNayyar** [comment]
Facing the same issue. Can we merge the PR if that already exists.

**Comment by harrysolovay** [comment]
+1

**Comment by shanchen** [comment]
+1

**Comment by holdenrehg** [comment]
+1

**Comment by wesbos** [comment]
The author of this is working on a browser based highlighter that works with VS Code themes. Still a WIP, but a quick demo I cooked up looks promising. 

I'm not sure what is involved with getting Polacode working for the time being - has anyone looked into it? 

<img width="663" alt="Screen Shot 2019-04-04 at 10 47 12 AM" src="https://user-images.githubusercontent.com/176013/55565056-20c87700-56c7-11e9-8079-300895645e9b.png">

**Comment by mralexho** [comment]
Not a solution!

But in case anyone needs a quick alternative, check out https://carbon.now.sh/.

**Comment by gabemeola** [comment]
Looks like this is being worked on recently.
https://github.com/octref/polacode/commit/8cdd0bcf35023df75b0515cdd90c1e15638e8752

**Comment by BobbyWibowo** [comment]
> Looks like this is being worked on recently.
> [8cdd0bc](https://github.com/octref/polacode/commit/8cdd0bcf35023df75b0515cdd90c1e15638e8752)

Yeah, `rewrite` branch is working for me here.

**Comment by pavanjadhaw** [comment]
See https://github.com/octref/polacode/issues/103#issuecomment-485533758

**Comment by Toxblh** [comment]
I fixed marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork
