### ISSUE TITLE
Polacode not working

### ISSUE THREAD

**Issue by AvatarRolon** [octref/polacode#102]
I tried to use polacode, but the extension fails for creating a new Screenshot, as you can see in the image below, the extension is continuously charging but never ends.
![image](https://user-images.githubusercontent.com/35464194/55740498-d1e54f00-59f0-11e9-9c70-473581076bc3.png)

**Comment by pavanjadhaw** [comment]
See https://github.com/octref/polacode/issues/103#issuecomment-485533758

**Comment by Toxblh** [comment]
I fixed marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork

**Comment by MrMoshkovitz** [comment]
I have The Same issue which has not solved

**Comment by tanesasasdam** [comment]
I have The Same issue ! 

![image](https://user-images.githubusercontent.com/70506592/95507111-8f7a4500-09ce-11eb-9188-b24753e33e98.png)

Is anyone have the solution ??

**Comment by tanesasasdam** [comment]
### PROBLEM SOLVED !!!!

**You can use this extension which looks same as POLACODE but it works !!**

![image](https://user-images.githubusercontent.com/70506592/95507649-51c9ec00-09cf-11eb-886b-6edeb29c7926.png)

Name: Polacode (fixed edition)
Id: mrrefactoring.polacode-fixed-edition
Description: 📸  Polaroid for your code (fixed for VSCode 1.47.0 and later)
Version: 0.3.6
Publisher: mrrefactoring
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mrrefactoring.polacode-fixed-edition


**OR YOU CAN ALSO USE** 

Name: CodeSnap
Id: adpyke.codesnap
Description: 📷 Take beautiful screenshots of your code
Version: 1.2.0
Publisher: adpyke
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap

![code](https://user-images.githubusercontent.com/70506592/95576164-93997780-0a4d-11eb-9708-0f7ec072d3f1.png)

**Comment by Hitesh-jadhav** [comment]
> I have The Same issue !
> 
> ![image](https://user-images.githubusercontent.com/70506592/95507111-8f7a4500-09ce-11eb-9188-b24753e33e98.png)
> 
> Is anyone have the solution ??

yes
i have the same one

**Comment by pritamSarkar123** [comment]
> ### PROBLEM SOLVED !!!!
> **You can use this extension which looks same as POLACODE but it works !!**
> 
> ![image](https://user-images.githubusercontent.com/70506592/95507649-51c9ec00-09cf-11eb-886b-6edeb29c7926.png)
> 
> Name: Polacode (fixed edition)
> Id: mrrefactoring.polacode-fixed-edition
> Description: 📸 Polaroid for your code (fixed for VSCode 1.47.0 and later)
> Version: 0.3.6
> Publisher: mrrefactoring
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mrrefactoring.polacode-fixed-edition
> 
> **OR YOU CAN ALSO USE**
> 
> Name: CodeSnap
> Id: adpyke.codesnap
> Description: 📷 Take beautiful screenshots of your code
> Version: 1.2.0
> Publisher: adpyke
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap
> 
> ![code](https://user-images.githubusercontent.com/70506592/95576164-93997780-0a4d-11eb-9708-0f7ec072d3f1.png)

I have tried it and it worked, thanks
