### ISSUE TITLE
Polacode stop working

### ISSUE THREAD

**Issue by GulajavaMinistudio** [octref/polacode#103]
Polacode in Visual Studio Code 1.33 not working. Try to open it from command, the screenshot palette not showing. Please fix it.

**Comment by Cosmoledo** [comment]
Yeah, same problem here. 

VSC:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Datum: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.15063

**Comment by kdbaustert** [comment]
VS Version 1.33.1

Broken for me as well

**Comment by xXFracXx** [comment]
Doesn't work ...

**Comment by valpinkman** [comment]
same here

**Comment by DeiverJC** [comment]
same problem for me in centos 7

**Comment by SayoBye** [comment]
same in win10

**Comment by Qhkm92** [comment]
Broken for me as well. Screenshot palette not displaying. 

VScode Version : 1.33.1

**Comment by minhqp** [comment]
Same here. Downgrade to older version is also not working as well.

**Comment by GulajavaMinistudio** [comment]
I think because some API changes in VS Code dan affect Polacode as well. Hope the developer can figure it out.

**Comment by xMentos5091** [comment]
Same problem here on Kubuntu 18.04 LTS

**Comment by GulajavaMinistudio** [comment]
@octref , can you figure it out ? any idea ?

**Comment by rochacbruno** [comment]
Also not working for me. I am using https://carbon.now.sh as a workaround (I use it to build my programming classes examples)

**Comment by PLASMAchicken** [comment]
The rewrite branch is working fine for me

**Comment by xMentos5091** [comment]
> The rewrite branch is working fine for me.
> Checkout the branch and run.
> 
> ```
> npm install -g vsce
> npm install
> vsce package
> ```
> This gives you an VISX wich you can install trough the Visual Studio Console by doing `Install Extension from VISX`

@PLASMAchicken  you right, it works!
Thank you

**Comment by doyle-mark** [comment]
> The rewrite branch is working fine for me.
> Checkout the branch and run.
> 
> ```
> npm install -g vsce
> npm install
> vsce package
> ```
> This gives you an VISX wich you can install trough the Visual Studio Console by doing `Install Extension from VISX`

Sorry, I don't quite follow what you mean, what would be the process for installing Polacode now?

**Comment by xMentos5091** [comment]
First clone the repo: 
``git clone https://github.com/octref/polacode``
After, go in repo folder and checkout rewrite branch:
``git checkout rewrite``
Now you can run the commands above (@PLASMAchicken's answer)

**Comment by doyle-mark** [comment]
@xMentos5091 Thank you very much sir :)

**Comment by doyle-mark** [comment]
FWIW, I have also tried installing from VISX from the rewrite branch, the polacode tab is still not opening. Essentially nothing is happening when I run polacode.

**Comment by xMentos5091** [comment]
What is your vscode's version?

**Comment by doyle-mark** [comment]
Hey, I'm on: **Version 1.33.1 (1.33.1)**

**Comment by xMentos5091** [comment]
I retried step by step and it works, very strange, are you sure that you did everything good?

**Comment by doyle-mark** [comment]
I've run exactly the commands listed above 😕

**Comment by Kerminate** [comment]
The same as mine...

**Comment by danghuynhdaty** [comment]
Hi there, i can not install vsix. Any idea?
![image](https://user-images.githubusercontent.com/31928624/56456256-fdbee800-6393-11e9-9044-5ef331623c2a.png)

**Comment by xMentos5091** [comment]
@danghuynhdaty 
Open vscode, after press **F1** or **ctrl+shift+p** to show all commands.
Write "Install Extension from VSIX" and run it.
After you'll need search the package that you created before.

**Comment by doyle-mark** [comment]
Is there a new update for Polacode update on horizon that will allow us to install the usual way rather then through the rewrite branch?

**Comment by frankhale** [comment]
I'm surprised somebody hasn't already forked the fork and added it to the  VS Code Marketplace by now... The Internet doesn't usually wait around. =)

But yeah, I just noticed Polacode is broken and I'm far too lazy to checkout the rewrite branch.

**Comment by rochacbruno** [comment]
First uninstall the current version of polacode.

```bash
git clone -b rewrite --single-branch https://github.com/octref/polacode
cd polacode
npm install vsce
npm install
./node_modules/vsce/out/vsce package
 DONE  Packaged: ./polacode-0.2.2.vsix (1930 files, 2.13MB)
```

Go to vscode and type 

Ctrl+Shift+P and then `Extensions: Install from VISX` choose `./polacode-0.2.2.vsix `

**Comment by itwasmattgregg** [comment]
The rewrite branch is giving me this dev tools error in vscode:
`[[object Object]]Cannot read property 'postMessage' of undefined`
VS Code version 1.33.1

**Comment by marques-p44** [comment]
Here's the error I see in the log when trying to run PolaCode: 
**VS Code 1.33.1**
**PolaCode 0.2.2**
```
'vscode.previewHtml' not found
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3027:549)
    at r.then.i (file:///Applications/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3027:430)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by marvin-solano** [comment]
Just as a reference: https://github.com/Microsoft/vscode/issues/62630

**Comment by Toxblh** [comment]
https://github.com/toxblh/polacode I fixed

**Comment by Toxblh** [comment]
Can create a PR if you want

**Comment by Cosmoledo** [comment]
> https://github.com/toxblh/polacode I fixed
> https://marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork

I don't know how to create a issue for this fork, so I will write them here.
After removing the polacode addon of the rewrite branch, I installed yours. It does only start at the first start of VSC. When I close the polacode tab and launch it again (through the console, F1), I do get the error "Running the contributed command: 'polacode-fork.activate' failed."
When I close VSC and start it again, polacode does work. And the cycle repeats.

**Comment by Toxblh** [comment]
> > [toxblh/polacode](https://github.com/toxblh/polacode) I fixed
> > [marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork](https://marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork)
> 
> I don't know how to create a issue for this fork, so I will write it here.
> 
> After removing the polacode addon of the rewrite branch, I installed yours. It does only start at the first start of VSC. When I close the polacode tab and launch it again (through the console, F1), I do get the error "Running the contributed command: 'polacode-fork.activate' failed."
> When I close VSC and start it again, polacode does work. And the cycle repeats.
> 
> Second issue/improvement:
> ![grafik](https://user-images.githubusercontent.com/26510897/57216590-8ecacb80-6ff0-11e9-9aaf-cc02cd608ebd.png)

done

**Comment by mohamedebrahim96** [comment]
i solve it by downgrade and update plugin again

**Comment by MetaMmodern** [comment]
Hi, not working on VSCode **v.1.48** Windows 10 2005. Any solution?

**Comment by Mamunoz42** [comment]
> Hi, not working on VSCode **v.1.48** Windows 10 2005. Any solution?

Yeeees, i have the same question.

**Comment by frankhale** [comment]
This is not an answer to why Polacode is not working but you may want to try out another extension until this one is fixed. I've been using CodeSnap and it's basically just like Polacode. https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap

**Comment by MetaMmodern** [comment]
> Hi, not working on VSCode **v.1.48** Windows 10 2005. Any solution?

Update July 2020 1.48.1, still not working

**Comment by MetaMmodern** [comment]
> This is not an answer to why Polacode is not working but you may want to try out another extension until this one is fixed. I've been using CodeSnap and it's basically just like Polacode. https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap

Awesome, thank you! even better than polacode)

**Comment by waffiqaziz** [comment]
> This is not an answer to why Polacode is not working but you may want to try out another extension until this one is fixed. I've been using CodeSnap and it's basically just like Polacode. https://marketplace.visualstudio.com/items?itemName=adpyke.codesnap

Thanks its very helpfull

**Comment by Elsenosy** [comment]
> https://github.com/toxblh/polacode I fixed
> https://marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork

Thanks
