### ISSUE TITLE
After using PolaCode, selecting any text copies it

### ISSUE THREAD

**Issue by duttaoindril** [octref/polacode#107]
I've noticed, very annoyingly, that every time I open up Polacode to take a picture and then close it, my clipboard is automatically replaced with whatever text I select. I have to restart my VS code window to fix the issue.

This is happening on VSCode, the latest Mac OS X 10.14.4 Mojave.

**Comment by octref** [comment]
That's how it works.

**Comment by duttaoindril** [comment]
Hi, that still continues even after I close PolaCode. That's not how it's supposed to work, right?

**Comment by octref** [comment]
I see, fixed, thanks.

**Comment by octref** [comment]
Published 0.3.1.

**Comment by duttaoindril** [comment]
Awesome, thank you so much!
