### ISSUE TITLE
Custom padding option

### ISSUE THREAD

**Issue by FatehAK** [octref/polacode#108]
Could you make it possible to include our own custom padding via a VS code setting? I think way too much padding is being added

**Comment by octref** [comment]
No, you can resize them.

**Comment by FatehAK** [comment]
With resizing you can only adjust the horizontal padding but not the vertical padding which makes it look uneven. Any way we can adjust the vertical padding?

**Comment by octref** [comment]
Can you include an image and explain what you want?

**Comment by FatehAK** [comment]
As you can see in [this](https://drive.google.com/open?id=1I_lTKwx7tjIcYmLPE5P5HvZwNQSYgL5M) video I am unable to adjust vertical padding

**Comment by octref** [comment]
I made it vertically centered:

![image](https://user-images.githubusercontent.com/4033249/57542556-e4f88100-7306-11e9-9c66-a07a965e8233.png)
