### ISSUE TITLE
Remember the "Save to" folder

### ISSUE THREAD

**Issue by johnpapa** [octref/polacode#11]
When saving, it always goes to desktop. Would be cool if it would remember where we saved it last time. (e.g. Download, documents, etc)

**Comment by ahmadawais** [comment]
I suspect this is where we need to create a Set to store the LRU cache type functionality to remember the last used save location instead of a default

https://github.com/octref/polacode/blob/215dbe6fa651d3c87d2321cbfbccdc3dfbe23aa0/src/extension.ts#L17

**Comment by octref** [comment]
@ahmadawais #17 is doable, but getting the placeholder colorized using the current theme is impossible without the user doing a copy-paste. I still want to show the placeholder each time.
