### ISSUE TITLE
polacode has nothing.

### ISSUE THREAD

**Issue by 44886** [octref/polacode#110]
![image](https://user-images.githubusercontent.com/10481933/58455543-8e87a100-8154-11e9-8947-7699bd5faf89.png)

is there anyone like this?

I used polacode-fork
![image](https://user-images.githubusercontent.com/10481933/58455576-a828e880-8154-11e9-98f9-b54101e776fd.png)

**Comment by posva** [comment]
that's not this extension, it is just polacode and the author will show Pine Wu
