### ISSUE TITLE
why it work only on ssh?

### ISSUE THREAD

**Issue by 44886** [octref/polacode#111]
I used the remote Remote Development , and when I install the polacode ,it only work on the ssh.

I want  save the image to local .

![image](https://user-images.githubusercontent.com/10481933/58469608-6ad35380-8172-11e9-9e4f-0aae324e3c66.png)

**Comment by ryanweaver718** [comment]
I was wondering the same, is there a work around for this?

**Comment by octref** [comment]
Extension in remote only has access to file system on remote machine.

**Comment by ryanweaver718** [comment]
Can you please explain how?

**Comment by octref** [comment]
https://code.visualstudio.com/api/advanced-topics/remote-extensions
