### ISSUE TITLE
Does it work with the "custom css and js" extension?

### ISSUE THREAD

**Issue by bratberg** [octref/polacode#112]
Is it possible to get polacode to also take into account the css color overrides being loaded with this extension: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css ?

**Comment by themarcba** [comment]
I'd like to know this as well. Hoping to accurately reproduce the Synthwave '84 theme

**Comment by octref** [comment]
Nope.

**Comment by conn7ctiv** [comment]
It would be very nice to have this working with my custom CSS/JS. Is it possible to implement, or add support for it through another extension?
