### ISSUE TITLE
Add command for "Save" so that we can create a keybinding for it

### ISSUE THREAD

**Issue by johnpapa** [octref/polacode#12]
first ... LOVE THIS, thank you!

This would enable this workflow, all via keyboard:

- CMD+A (select all)
- CMD+C (copy)
- CMD+CTRL+I (i mapped this to activate polacode)
- CMD+V (paste to polacode)
- .... now we use the mouse/trackpad to press the save button in polacode

I propose a command that we can map to a keybinding for the final step.

What do you think?

**Comment by octref** [comment]
That's reasonable. I'll try to ensure the command saves the file but also plays the aperture animation :)

**Comment by johnpapa** [comment]
Thanks. I love anything that keeps my fingers on the keyboard

**Comment by octref** [comment]
@johnpapa After you activate Polacode, you can bind `polacode.shoot` now. I'll keep using this command name for save.

These commands are dynamically registered, so make sure you activate Polacode first.

![image](https://user-images.githubusercontent.com/4033249/36355346-9b300ae0-1496-11e8-919f-7f0de54d4f75.png)

**Comment by johnpapa** [comment]
thanks, i will try it in the next release/update

**Comment by johnpapa** [comment]
Tried it, works great! Thank you!

https://twitter.com/John_Papa/status/965926631784185858
