### ISSUE TITLE
Ligatures not working

### ISSUE THREAD

**Issue by kufii** [octref/polacode#120]
I have editor.fontLigatuers enabled but polacode screenshots render them without. I've tried it with several different fonts and none of them work.

**Comment by lozandier** [comment]
@kufii @octref FYI:  Version `0.3.4` renders ligatures of my ligature-capable  fonts to suddenly no longer work such as `'PragmataPro Liga'`.

Rolling back to `0.3.3` fixed the issue.

Accordingly, the change may need to be tweaked unless I'm mistaken to think it's part of `0.3.4`.

**Comment by lozandier** [comment]
**`0.3.4` Result**
![0 3 4-result](https://user-images.githubusercontent.com/1223224/67089109-b5725e00-f15b-11e9-9d0a-165dcba12aa8.png)

**0.3.3 Result after rolling back**
![example-snippet](https://user-images.githubusercontent.com/1223224/67089179-e5216600-f15b-11e9-9b27-189971424e07.png)

**Comment by lozandier** [comment]
Nevermind, just realized `0.3.4` is a *rollback* of this change because of background regression.

**Comment by jLouzado** [comment]
so should this issue be reopened then?

**Comment by lozandier** [comment]
This should be re-opened. The latest version I constantly need to revert from to have ligatures be re-enabled.

@octref
