### ISSUE TITLE
Suggestion: use selected text instead of requiring pasting

### ISSUE THREAD

**Issue by chriskrycho** [octref/polacode#14]
It would be awesome if, instead of having to do the copy-and-paste dance, you could simply select some text and then run the command. VS Code [exposes the `TM_SELECTED_TEXT` variable](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) for snippets, and I'm wondering if there's a way to reuse that here?

**Comment by chriskrycho** [comment]
Follow-up: looks like what you *actually* would want to do this is to use the [`registerTextEditor`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#commands.registerTextEditorCommand) command, which gives you access to a [`TextEditor`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor) instance, including any current selections.

**Comment by octref** [comment]
@rebornix Correct me if I'm wrong, but I don't think it's possible unless VS Code offers a way to export the HTML of the selection.

**Comment by elboletaire** [comment]
But can't you run the copy + paste command when executing the `Polacode` command?

**Comment by pmolaro** [comment]
PLUS 1 for this feature.  
I'd prefer to: Highlight code, run Pola, get the custom image in the new window for me to save.  Just remove the 2 extra steps of copy and paste.

**Comment by octref** [comment]
![sel](https://user-images.githubusercontent.com/4033249/36519701-ca0b0088-1741-11e8-891e-8c0f46118e96.gif)
