### ISSUE TITLE
Not working after opening

### ISSUE THREAD

**Issue by umair313** [octref/polacode#147]
I am using VS Code version 1.50.1 install the extension but after opening I highlight code and copy code but it did not appear in polacode I am just seeing a Lense Ison but nothing also happening on clicking on it

**Comment by haulinh** [comment]
The same goes for me
![image](https://user-images.githubusercontent.com/26776857/97076015-b8741a00-160b-11eb-823d-eea0cf765a4b.png)

**Comment by Tammer1337** [comment]
Same here

**Comment by adstep** [comment]
Yup broken here too.

**Comment by umair313** [comment]
I think developers are not working on it anymore

**Comment by zhu-hongwei** [comment]
same too. I have a screen shot, but couln't submit on the github.

**Comment by umair313** [comment]
I am Closing this issue now I think the developer is not working it on anymore but
guys you can use an alternative here it is [Carbon](https://carbon.now.sh/) it's good I am now using it.
