### ISSUE TITLE
Does not respect wrapping, code gets cut off

### ISSUE THREAD

**Issue by smlombardi** [octref/polacode#15]
If the code block is wider than the polacode window, it's simply cut off:

![code](https://user-images.githubusercontent.com/835148/36316622-c679a5c4-1308-11e8-929e-764715bdeec9.png)

**Comment by ryzokuken** [comment]
Came here just to file this issue

<img width="1680" alt="screen shot 2018-02-16 at 9 45 16 pm" src="https://user-images.githubusercontent.com/13121330/36317487-3ad9313c-1363-11e8-9747-100ff8b893d6.png">

**Comment by octref** [comment]
We'll track it in #4.
