### ISSUE TITLE
The extension just doesn't work

### ISSUE THREAD

**Issue by len0xx** [octref/polacode#156]
I have installed the extension, reloaded the VSCode and it still doesn't do anything but showing me an icon
I tried to copy/paste the code — nothing again.

![image](https://user-images.githubusercontent.com/21990466/103478410-52b0c500-4de8-11eb-9edb-2be66fe2a917.png)

**Comment by ferrinweb** [comment]
I also encountered this problem.

**Comment by YouAndMe8342** [comment]
Me, too...

**Comment by len0xx** [comment]
#143 fixed this issue.
Try installing _fixed_ version:
https://marketplace.visualstudio.com/items?itemName=mrrefactoring.polacode-fixed-edition
