### ISSUE TITLE
Polacode not reacting

### ISSUE THREAD

**Issue by baimamboukar** [octref/polacode#160]
Nothing happens when I select my code.......... Any solution to this problem ?

**Comment by Lufen34** [comment]
Same for me on Opensuse as my Linux distro.

**Comment by Dkb743** [comment]
I don't know the reason but if you copy and paste in the polacode window it works but doesn't give preview when you select lines of code.

**Comment by baimamboukar** [comment]
> I don't know the reason but if you copy and paste in the polacode window it works but doesn't give preview when you select lines of code.

Alright then ! If it is working with copy-paste.....

**Comment by 2catycm** [comment]
same on my computer
