### ISSUE TITLE
Bug: Text overflows outside of the box

### ISSUE THREAD

**Issue by TorzuoliH** [octref/polacode#18]
Hey! Congrats for this great project!

I was testing it, and found a bug on some small width.

If line is too long, it overflows outside of box.

Maybe it box shouldn't be resized with VSCode panel, but more regarding text length?

![img](https://i.imgur.com/whd7dpY.png)

I'm on macOS 10.13.1, VSCode 1.20.1.

Regards

**Comment by octref** [comment]
Thanks for the report. This is being tracked in #4.

**Comment by TorzuoliH** [comment]
Oh yes sorry, I didn't check closed issues!
