### ISSUE TITLE
Sublime Text Support

### ISSUE THREAD

**Issue by stach** [octref/polacode#23]
> Please support the Sublime Text code editor in the future.

**Comment by niladam** [comment]
I second this.

**Comment by ethanent** [comment]
While I completely agree with the sentiment here, I think that it'd be a bit complex to convert polacode to a Sublime-and-VS Code plugin / Package Control package as the two likely have very different APIs. (It'd involve a rewrite likely.)

**Comment by octref** [comment]
Sublime do not have webview and copy-with-syntax-highlighting features so it's impossible.

**Comment by MalindaWMD** [comment]
There's a package now called [Carbon](https://github.com/molnarmark/carbonSublime)
