### ISSUE TITLE
VS code half-screen generate narrow image

### ISSUE THREAD

**Issue by AlexanderLiuzm** [octref/polacode#24]
### Hi there,
I installed polacode in VS code, win10. I set my VS code to half screen, then try to generate a picture, finally I got this:
![code](https://user-images.githubusercontent.com/20107871/36341592-a146b12e-142b-11e8-9a3b-4ec8ccf5a8d4.png)

**Comment by octref** [comment]
You can track #4 for updates.

**Comment by octref** [comment]
Or try `View: Toggle Editor Group Vertical/Horizontal Layout` for more horizontal space.
