### ISSUE TITLE
Pasted content is invalid. Only copy from VS Code and check if your shortcut for copy/paste have conflict

### ISSUE THREAD

**Issue by imamaris** [octref/polacode#26]
How to solve this problem? i see ctrl+c any shortcut keybinding in my VSCode

**Comment by octref** [comment]
You need to make sure you are selecting and copying from VS Code. If you are already doing that, search for `Ctrl C` and `Ctrl V` in Shortcut Editor: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by jenewland1999** [comment]
@octref I'm getting this very same problem however, even after changing keybindings it still is not working 😕

**Comment by evenfrost** [comment]
Not working for me as well. Disabled all extensions but it still says `Pasted content is invalid.`. Tried <kbd>CTRL</kbd>+<kbd>C</kbd> <kbd>CTRL</kbd>+<kbd>V</kbd>, `Copy` and `Paste` commands from context menu but still nothing. @octref please reopen as it is definitely an issue and affects multiple users.

**Comment by octref** [comment]
See https://github.com/octref/polacode/issues/28#issuecomment-366732059

**Comment by evenfrost** [comment]
@octref https://github.com/octref/polacode/blob/b650999f7c5f5ada3107c7730db621fbdd0936a9/src/webview/index.js#L98-L99

Here you're trying to retrieve HTML data on paste, but `startsWith` check fails if a JavaScript chunk is pasted (`e.clipboardData.getData('text/html')` returns empty string in this case).

So, I've tried to copy/paste a HTML chunk, but it errored as well. This is because `e.clipboardData.getData('text/html')` returned HTML string starting from `<meta http-equiv="content-type" content="text/html; charset=utf-8">` (instead of just `<meta charset='utf-8'>`).

Though I tested it in Chrome console, I'm pretty sure this is the case for VSCode environment as well (same engine). Seems to be similar to https://github.com/octref/polacode/issues/28 issue.

FWIW, this is the code I used in Chrome console:
```js
document.addEventListener('paste', e => {
  const innerHTML = e.clipboardData.getData('text/html');
  console.log(innerHTML);
});
```

**Comment by gnapse** [comment]
I'm having this issue too, in macOS, right off the bat after installing the extension, so I'm not sure why this issue is closed. It should be open until it's fixed.

**Comment by amiralies** [comment]
same here

**Comment by octref** [comment]
@evenfrost Thanks for the info! I thought the meta info come from VS Code, but it's actually Chrome (or Electron, to be specific).

I've pushed a fix. Try upgrade to 0.2.1.

**Comment by modestfake** [comment]
@octref Hi. I've just tried this one:
```javascript
document.addEventListener('paste', e => {
  const innerHTML = e.clipboardData.getData('text/html');
  console.log(innerHTML);
});
```

and my `iinerHTML` starts with `<html><body>`

My OS is Windows 10

**Comment by evenfrost** [comment]
@octref Thanks for the update! After installing `0.2.2` the issue is gone.

**Comment by gnapse** [comment]
I'm sorry, I'm not sure what I'm doing wrong, but now I paste into the Polacode view and nothing happens 😞

**Comment by octref** [comment]
@gnapse check if your copy paste shortcuts are overrided.

**Comment by gnapse** [comment]
@octref  doesn't look like that's the problem, but I'm not familiar with this view so judge yourself:

![image](https://user-images.githubusercontent.com/15199/36433816-3a590cba-163c-11e8-9bc9-87462bf53ea8.png)

**Comment by octref** [comment]
@gnapse 
Can you try this

- Open Polacode window
- Run command Developer: Webview Tools
- In the Chrome Dev Tool, Cmd/Ctrl - P - index.js
- Below this line `const innerHTML = e.clipboardData.getData('text/html')`, add `console.log(innerHTML)`.

**Comment by gnapse** [comment]
@octref Wow nice! I did not know you could launch a web devtools of stuff in vscode.

Anyway, this is the screenshot. Apparently, after the clipboard content is received correctly, an error occurs.

<img width="912" alt="screen shot 2018-02-20 at 3 15 54 pm" src="https://user-images.githubusercontent.com/15199/36441330-09355052-1651-11e8-8214-f1401287a1b7.png">

**Comment by gnapse** [comment]
Oh yeah, not it works, copying using that command. But I always thought this worked with a plain old Cmd+V. Or do you mean that Cmd+V normally copies with syntax highlight? Why would it do that? Wouldn't that interfere with my normal copying in other contexts, when I only want the actual plain text of the code?

**Comment by octref** [comment]
> Cmd+C normally copies with syntax highlight

Yes.

> Wouldn't that interfere with my normal copying in other contexts

No. Programs mostly read them as `text/plain` so they only get the plain text, not the HTML with syntax highlight.

**Comment by gnapse** [comment]
Ok, after disabling some of my extensions one by one, I realized is this one: [vscodevim.vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim). Anyway, seems to be its fault and not this extension's fault. I just share it here to further close the issue.

**Comment by octref** [comment]
You should Remove its keybinding for Cmd+C

![image](https://user-images.githubusercontent.com/4033249/36447044-0460a2f2-1638-11e8-9667-111793931749.png)

But thanks for reporting the issue!

**Comment by imamaris** [comment]
which changed? keybinding command which to use polacode, see picture below ;
![2018-02-21 1](https://user-images.githubusercontent.com/17156649/36463543-38531b88-16fd-11e8-806b-7f205171c14f.png)
![2018-02-21](https://user-images.githubusercontent.com/17156649/36463544-3886305e-16fd-11e8-822e-9aa517067987.png)
