### ISSUE TITLE
Improve shadow

### ISSUE THREAD

**Issue by equinusocio** [octref/polacode#27]
Hi, the generated image have the shadow cropped at the bottom. Would be awesome have a way to export transparent png with no shadows and/or add more space at the bottom to avoid shadow cropping

**Comment by octref** [comment]
Yep, shadow now look ugly on white themes. 

I'll keep #29 as the one for switching off shadow and backdrop and leave this one for improving the shadow.

**Comment by MaxMcKinney** [comment]
@octref Is there a timeline for implementing more padding to allow the shadow to fade into it's background?
