### ISSUE TITLE
Provide a way to switch off shadow and backdrop

### ISSUE THREAD

**Issue by DenysVuika** [octref/polacode#29]
The resulting image contains an ugly (sorry) shadow that causes the image to look bad on white pages. Please provide a way to switch it off.

<img width="825" alt="screenshot 2018-02-19 21 06 53" src="https://user-images.githubusercontent.com/503991/36397060-df757bae-15b8-11e8-9cba-978d1de81d39.png">

**Comment by MichMich** [comment]
+1, please allow us to disable it. Thanks!

**Comment by octref** [comment]
Without shadow backdrop should go away, too.

**Comment by angelhdz** [comment]
Please!

**Comment by octref** [comment]
You can configure it with `polacode.shadow`.
