### ISSUE TITLE
Nothing happens when pasting into polacode window

### ISSUE THREAD

**Issue by mtharrison** [octref/polacode#3]
Not sure if I'm doing something wrong but I followed the steps:

1. Run polacode command
2. Copy my code
3. Paste into polacode window
4. Nothing happens / The code in the image doesn't change

Versions:

VSCode version 1.20.1 (1.20.1)
Mac OSX High Sierra 10.13.3

**Comment by octref** [comment]
Do you have Vim extension?

If so you need to remove its Cmd+C keybinding...I'm thinking about how to address this.

Vim copies code into clipboard without the html.

**Comment by mtharrison** [comment]
No, I don't have the vim extension. I just disabled all my extensions and tried again but have the same issue.

**Comment by mtharrison** [comment]
I guess it's an issue with a keybinding. I tried edit menu -> paste and that works just fine.

**Comment by octref** [comment]
Check if there is anything that overlapped with your Paste command's shortcut.

Let's say you have Cmd+V. Search that in the keybinding editor.

![image](https://user-images.githubusercontent.com/4033249/36292423-99c92180-1286-11e8-928e-099b92e88720.png)

**Comment by chriskrycho** [comment]
Seeing the same thing – **Edit** -> **Paste** works, but Cmd V does not.

<img width="351" alt="keybindings" src="https://user-images.githubusercontent.com/2403023/36313100-c75a98a6-12ed-11e8-8828-06bac639ba77.png">

**Comment by octref** [comment]
@chriskrycho Why you have two paste? Can you also show me the `source` and `when`?

**Comment by mtharrison** [comment]
I had a bunch. No idea where they came from tbh but I've removed them now.
![screen shot 2018-02-17 at 00 08 09](https://user-images.githubusercontent.com/916064/36319810-b738a6d2-1376-11e8-99f7-5468b56aea7d.png)

**Comment by mtharrison** [comment]
It works great now, thanks for the cool extension. I can think of many uses for it. Feel free to close this issue if you want.

**Comment by octref** [comment]
I added a warning message when pasted content is not HTML (the format where copy in VS Code puts in clipboard)

![image](https://user-images.githubusercontent.com/4033249/36357717-c1023aac-14b6-11e8-90f0-f3a342bd2117.png)

**Comment by mvolkmann** [comment]
It certainly seems that this does not work when the Vim extension is installed.

**Comment by sachinwalunjakar** [comment]
Instead of copying text using key binding, copy code by right-clicking and selecting copy
Then paste in polacode with "cmd-v". That works!
