### ISSUE TITLE
Request: Port to Atom/Sublime?

### ISSUE THREAD

**Issue by DrewDouglass** [octref/polacode#34]
Does anyone know of a similar tool for Atom? This is really neat. If not, I assume this would need to be completely re-written for Atom (not easily portable)?

Again, great work.

**Comment by octref** [comment]
Sublime - #23.
Atom - I’m not familiar with its API and I don’t have time for it. You can do your port, but you cannot reuse my logo or the Polacode name.

**Comment by karanganesan** [comment]
@atom Any Help ??

It will be very cool having it on atom also !!!

**Comment by nurtext** [comment]
@DrewDouglass 
See https://atom.io/packages/screenshot

**Comment by DrewDouglass** [comment]
@nurtext Thanks for the helpful response. Appreciate it!

**Comment by nurtext** [comment]
@DrewDouglass Welcome :)

**Comment by jacobwarduk** [comment]
@octref

 > You can do your port, but you cannot reuse my logo or the Polacode name.

My understanding of the MIT license - which this software is released under - may be flawed. 

However, I believe @DrewDouglass  _can_ use the logo and Polacode name for any derivative works. 

Please correct me if I'm wrong.

**Comment by octref** [comment]
The license don’t apply to name and media. It’s only for code.

**Comment by jacobwarduk** [comment]
@octref Okay, cool. Just wanted to clarify.

**Comment by envygeeks** [comment]
I am not a lawyer but this is pretty obvious. You can restrict the usage of a logo, it's automatic copyright... as artwork, you cannot however restrict the usage of a name, or even ask somebody to remove said software with the same name... unless you've a trademark.  You can't copyright a name.

**Comment by octref** [comment]
@envygeeks You are right. I cannot legally exclude you from using the name Polacode. However, I don't hope you name a port as Polacode, as the same name implies possible relationship and endorsement.

**Comment by envygeeks** [comment]
No worries from me, I'm not that kinda person.
