### ISSUE TITLE
Auto wrap for long lines

### ISSUE THREAD

**Issue by octref** [octref/polacode#4]
- Add option to specify image width (and wrap on that width)
- Read `editor.wordWrapColumn` and wrap on it

**Comment by alexsasharegan** [comment]
Could this possibly be read from a default vscode setting? That way we don't have to hunt down another extension config? Maybe this:

```json
{ "editor.wordWrapColumn": 80 }
```

**Comment by octref** [comment]
Word wrap is too much complexity. Decided to just wrap on each token (words).

**Comment by octref** [comment]
![code](https://user-images.githubusercontent.com/4033249/36355187-96740864-1494-11e8-82c0-45d101479850.png)

**Comment by alexsasharegan** [comment]
That works!
