### ISSUE TITLE
Broken when Vim plugin enabled

### ISSUE THREAD

**Issue by benawad** [octref/polacode#41]
Doesn't seem to work when I have https://github.com/VSCodeVim/Vim enabled.

**Comment by octref** [comment]
https://github.com/octref/polacode/issues/35 and https://github.com/octref/polacode/issues/26

In short, remove Vim's keybindings for Copy/Paste or use setting
```
  "vim.overrideCopy": false
```

However with #14 this won't be an issue any more in new release.
