### ISSUE TITLE
Code Insiders - `end of central directory record signature not found`

### ISSUE THREAD

**Issue by MrCroft** [octref/polacode#43]
When I try to install the extension on Code Insiders (currently 1.21.0) I get the message:
```
 end of central directory record signature not found
```
And the extension doesn't install.
I've randomly tried other extensions (not to mention I already have quite a few installed, so I guess it's not a problem with Code).

**Comment by octref** [comment]
I found this issue: https://github.com/Microsoft/vscode/issues/42229

I'm guessing you are using a proxy server? Anyway this should be reported to VS Code, not this extension.

**Comment by MrCroft** [comment]
@octref I've found that issue also. But I'm not using a proxy. I didn't mention that I'm not using a proxy because I thought that being able to install any other extension implied that it's not that issue.
Anyway, for the time being I've managed to install it from disk, after downloading the extension.

**Comment by octref** [comment]
@MrCroft Would you mind following up with @joaomoreno at https://github.com/Microsoft/vscode/issues/42229? This could be affecting many other users too.

**Comment by spences10** [comment]
Chiming in here, I have the same error when trying to install - I'm not using a proxy either

**Comment by octref** [comment]
This is a VS Code issue that's possibly caused further upstream by `yauzl`. See https://github.com/Microsoft/vscode/issues/42229#issuecomment-369305334 if you are interested.

Meanwhile if uninstall -> install does not work, try removing the `pnp.polacode-0.2.2` folders from your extension folder and reinstall. If still no luck, try using the VSIX package to install

https://pnp.gallery.vsassets.io/_apis/public/gallery/publisher/pnp/extension/polacode/0.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by spences10** [comment]
Ok, there was no `pnp.polacode` file or folder in `%USERPROFILE%\.vscode\extensions`

Tried to load the linked extension and for some reason it won't load in code

I used the `code --install-extension ` to install it and renamed it from what it was to `code --install-extension myextension.vsix`
