### ISSUE TITLE
Font ligatures rendered when "editor.fontLigatures": false

### ISSUE THREAD

**Issue by hectahertz** [octref/polacode#44]
Current settings:

```JSON
    "editor.fontLigatures": false,
    "editor.fontFamily": "'Fira Code', Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14,
```
Fira Code from: https://github.com/tonsky/FiraCode

Editor view:
<img width="682" alt="screen shot 2018-02-23 at 15 29 38" src="https://user-images.githubusercontent.com/24622853/36599047-66b934a0-18ae-11e8-8849-df2c4cc69bc4.png">

Polacode:
![code](https://user-images.githubusercontent.com/24622853/36598998-363c58d4-18ae-11e8-816c-c5e59b19fe3d.png)

Expected:
Polacode only renders ligatures when `"editor.fontLigatures": true`

**Comment by octref** [comment]
Great find -- VS Code doesn't export font-ligature settings yet. However this can be worked around.

**Comment by misterabd** [comment]
Hello, what's the workaround?

**Comment by wreckursive** [comment]
@hectahertz which VSCode theme is this, btw? Thanks!
