### ISSUE TITLE
Not working from unsaved tab

### ISSUE THREAD

**Issue by cfjedimaster** [octref/polacode#45]
I had some code in a slide I wanted to Polacode on so I opened up a new tab in Code, pasted in my code, then copied it *again* and pasted it into Polacode but it wouldn't accept the input.

I saved the file and then I was able to paste it in.

**Comment by cfjedimaster** [comment]
If it requires a saved file so it knows what color coding to use, that's fine, but maybe it should be documented? (I looked but didn't see anything.)

**Comment by octref** [comment]
If the tab you pasted in doesn't get highlight, you don't get highlight in Polacode.
