### ISSUE TITLE
Feature Request: Mac-style Window UI Buttons

### ISSUE THREAD

**Issue by lukefiji** [octref/polacode#46]
I feel like adding Mac-style UI buttons like in [Carbon](https://carbon.now.sh/) would add to the aesthetic. If you'd like, I just created a set in Sketch, exported them to SVG and ran them through [SVGOMG](https://jakearchibald.github.io/svgomg/). You can grab my resulting SVG on a [Codepen pen I just created](https://codepen.io/lukefiji/pen/OQoyxR).

**Comment by twhite96** [comment]
I'd like this a lot. Maybe make it optional? This is the one thing I will miss most from Carbon.

**Comment by octref** [comment]
Sorry but no. Polacode works cross-platform so I'm against adding indication of single-platform.
