### ISSUE TITLE
Doesn't work when VSCodeVim plugin is enabled

### ISSUE THREAD

**Issue by osenvosem** [octref/polacode#48]
Just nothing happens when you paste code to polacode tab. But it works fine if you disable the plugin.

**Comment by ellsclytn** [comment]
Right click to copy seems to work, while Ctrl/Cmd + C doesn't 🤔

**Comment by uesteibar** [comment]
Even with right click to copy, doesn't work for me. Also tried setting `vim.useSystemClipboard` to `false`, but doesn't seem to fix it.

**Comment by octref** [comment]
With the next version you don't need copy-paste anymore:

![sel](https://user-images.githubusercontent.com/4033249/36519701-ca0b0088-1741-11e8-891e-8c0f46118e96.gif)

**Comment by trustin** [comment]
It's not released yet, right? Looking forward to it!
