### ISSUE TITLE
Allow responsive html export

### ISSUE THREAD

**Issue by octref** [octref/polacode#5]
Currently the extension makes images, which are awesome for speaking & tweeting, but not so much for embedding into blog posts.

We should have a way of exporting responsive html, so people can embed the output and have the code copy-pastable.

**Comment by collegeimprovements** [comment]
This would be huge. Awesome.

**Comment by sangeeth96** [comment]
By this do you mean we need to have the embed support the theme/font used?

**Comment by octref** [comment]
[Whetting your appetite](https://shiki.matsu.io) :p

![shiki](https://user-images.githubusercontent.com/4033249/47977496-2ca70300-e06d-11e8-8ab3-77b26ccda611.png)

**Comment by octref** [comment]
Here you go https://shiki.matsu.io.
