### ISSUE TITLE
Handle long token gracefully

### ISSUE THREAD

**Issue by menjilx** [octref/polacode#51]
Hi
Anyone encountered the same issue?

![image](https://user-images.githubusercontent.com/14908836/36883495-ab34c236-1e15-11e8-9728-97134dfea64b.png)

Thanks

**Comment by octref** [comment]
This happens when you have tokens that's too long. In your case, the URL.

I suggest you resize Polacode window for now to get best result. I'll see if I can handle this gracefully.

**Comment by trustin** [comment]
May be related: #53

**Comment by Sh1noka** [comment]
I am also having this issue. My case is a markdown file of CJK characters. They all overflow.

And I try to not split the view and use only one view, but nothing shows, even the instruction picture.

**Comment by octref** [comment]
@Sh1noka Open new issue please. This one should be outdated since #104 and #105.
