### ISSUE TITLE
Won't install - end of central directory record signature not found

### ISSUE THREAD

**Issue by will-hancock** [octref/polacode#54]
Sorry do'm have any more debug info than this;

macOSX
Code version 1.20.1

Shows this error message when trying to install.

![image](https://user-images.githubusercontent.com/2384582/37088767-5a35ef1a-21f6-11e8-94a8-23c6de938c05.png)

**Comment by ovinn** [comment]
Same for Windows 10

**Comment by jacktuck** [comment]
Mind trying to update? 1.21.0 is out

**Comment by will-hancock** [comment]
@jacktuck yep fixed with todays update

**Comment by will-hancock** [comment]
Closing
