### ISSUE TITLE
Can't install. End of central directory record signature not found

### ISSUE THREAD

**Issue by m2de** [octref/polacode#58]
When I try to install version 0.2.2 I get an error message and the extension doesn't install. Have installed other extensions without problem so don't think it is related to my setup.

`End of central directory record signature not found`

VS Code: 1.20.1
Mac OS X: 10.13.3

**Comment by egamma** [comment]
@octref I can reproduce the problem on Windows in both stable and insiders. It looks like a marketplace issue.

**Comment by octref** [comment]
@egamma OK thanks, but @m2de is on macOS...

@m2de Can you try this?

- Run command `Extensions: Open Extensions Folder`
- Delete all `pnp.polacode` folders
- Try install it again

**Comment by egamma** [comment]
@pine actually, we can also be reproduce this on OS X. We also observed that an install from inside VS Code will use the chromium/electron disk cache and therefore you get the corrupt version again. 

A work around that has worked here is to do a manual download and install (available from the error notification), which will download the extension through the browser.

**Comment by octref** [comment]
@egamma Thanks for the explanation

@m2de So the solution now seems to be:
- Download https://marketplace.visualstudio.com/_apis/public/gallery/publishers/pnp/vsextensions/polacode/0.2.2/vspackage
- Install the VSIX file https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by m2de** [comment]
Thanks for the update. Downloading and installing it manually works for me, although I'm not sure I'd consider it a fix, there could be a lot of other users with the same issue who won't think to research a workaround on Github ;)

**Comment by egamma** [comment]
@m2de agreed more users could be affected and we are tracking the issue with the market place team. Since the issue is an upstream issue with the marketplace and not a polacode issue, closing the issue makes sense.

**Comment by sandy081** [comment]
I am tracking this with Marketplace team, will update as soon as I get updated.
