### ISSUE TITLE
Adjust image size

### ISSUE THREAD

**Issue by PterPmnta** [octref/polacode#66]
It would be important to take the width and length of the amount of code that one copies, both high and wide

![Alt Text](https://i.imgur.com/wFlkrIY.png)

**Comment by mittalyashu** [comment]
![code](https://user-images.githubusercontent.com/29014463/41700900-ecb2eb82-7547-11e8-87d1-80b118b5bf6b.png)

Text is getting out of the screen.

**Comment by muuvmuuv** [comment]
Better would be an option to specify a max_width value for social media profiles so it wont get bigger regardless of the view size
