### ISSUE TITLE
Too much padding before and after content

### ISSUE THREAD

**Issue by tornography** [octref/polacode#7]
There is too much padding before and after the content.
Even `View: Toggle Editor Group Vertical / Horizontal layout` does not help.
![padding](https://user-images.githubusercontent.com/878616/36300201-83c9a268-1300-11e8-897e-e95f3c601fc8.png)

System: Windows 10

**Comment by octref** [comment]
That's how single line looks on macOS.

![code](https://user-images.githubusercontent.com/4033249/36322594-bcf80050-1302-11e8-9018-21c2215e12e7.png)

The padding is definitely not right for Windows. I'll look into it.
