### ISSUE TITLE
Ship the new version to store

### ISSUE THREAD

**Issue by Yukaii** [octref/polacode#71]
Just installed latest polacode from Marketplace (version 0.2.2), which seemed to not include the commit https://github.com/octref/polacode/commit/0ed0338f9fb649af0ef86019aa391b902d5ec940. This is absolute a necessary feature for VSCodeVim users like me. Please please to upgrade it. 😍

**Comment by gee-forr** [comment]
Yeah - this extension doesn't work for me either because I'm using VSCodeVim too. :(
