### ISSUE TITLE
[feature request] Add better comments support

### ISSUE THREAD

**Issue by ReasonableDeveloper** [octref/polacode#81]
Hey, thank you for this great extension. I was wondering if it is possible to get syntax highlighting and strikethrough support for the [better comments extension](https://github.com/aaron-bond/better-comments).

![image](https://user-images.githubusercontent.com/28842311/46564568-55ba6380-c908-11e8-9a5d-2fe0fe848ad5.png)

**Comment by octref** [comment]
Not easily doable.
