### ISSUE TITLE
Does not work with operator mono font.

### ISSUE THREAD

**Issue by xereda** [octref/polacode#85]
This extension does not work with operator mono font.
See attachments.

![peek 30-11-2018 16-39](https://user-images.githubusercontent.com/14337850/49308163-a8ef0380-f4be-11e8-909f-9e7af2f61900.gif)

**Comment by kiliman** [comment]
Perhaps this issue can be closed. It works fine for me with Operator Mono. Including ligature support.
![code](https://user-images.githubusercontent.com/47168/57336827-5365f500-70f5-11e9-8e43-89d871ece36b.png)

**Comment by xereda** [comment]
For me it's working now.
