### ISSUE TITLE
VS Code Hangs after Shutter Click

### ISSUE THREAD

**Issue by danchamorro** [octref/polacode#89]
Just today VS Code will crash after I hit the shutter button to take the screenshot. Never was an issue before. I don't have VIM installed. Uninstalled and reinstalled Polacode. The only plugin I added since it last worked was Angular Snippets.

**Comment by octref** [comment]
Are you using insiders version?

**Comment by danchamorro** [comment]
I am using version 0.2.2

**Comment by octref** [comment]
I mean VS Code version. But you probably aren't.

If you run the command `Developer: Open Webview Developer Tools` before you press shutter, any error there?

**Comment by danchamorro** [comment]
No console errors or any error.

**Comment by danchamorro** [comment]
Vs Code: Version 1.30.2 (1.30.2)

**Comment by danchamorro** [comment]
My Mac, in general, has been acting up, so I don't think it was just a polacode thing. Did a factory restore and everything is working as intended

**Comment by octref** [comment]
Oh well, good luck.
