### ISSUE TITLE
Pasting via cmd+v not working

### ISSUE THREAD

**Issue by Brocco** [octref/polacode#92]
VS Code version: 1.31.0-insider
(this is using VS Code Insiders build)

**Current Behavior**
Copy the code from my editor
Focus the polacode window/pane/tab
Press cmd+v
Nothing happens
In the Edit menu click Paste
My text appears as an image in polacode

**Expected Behavior**
When I paste via cmd+v my text appears in polacode

**Additional Information**
- I have verified that I do not have any keybindings that would overwrite this behavior
- When verifying my keybindings I noticed the "when" for paste states "`textInputFocus && !editorReadonly`".

Note: I recognize that this may be an issue stemming from a change in VS Code as I'm on the Insiders build, but wanted to file the issue here for visibility.

**Comment by michaeljota** [comment]
Using for Stable VSCode release, I can confirm the issue.

**Comment by Brocco** [comment]
Closing this... it is fixed in the latest insiders build.

@michaeljota I would presume this will propagate to the next stable release.
