### ISSUE TITLE
Deprecation of _workbench.htmlPreview. 

### ISSUE THREAD

**Issue by Rietty** [octref/polacode#94]
Was building and playing around with this from source, and noticed that VSCode gave a warning on the usage of `_workbench.htmlPreview` and to shift it to: https://code.visualstudio.com/api/extension-guides/webview API.

Was wondering if this was planned for the future?

**Comment by octref** [comment]
Yes, I'll move off to webview.

**Comment by coding-saints** [comment]
this is still breaking the polacode extension: `vscode.previewHTML'

**Comment by ktowen** [comment]
Any progress here?
