### ISSUE TITLE
Polacode don't work on the new update 

### ISSUE THREAD

**Issue by DRXDesign** [octref/polacode#97]
![image](https://user-images.githubusercontent.com/3410550/53192498-e58a5100-360e-11e9-878b-01e66f64d9dc.png)

**Comment by doroncy** [comment]
this is the error VSCode shows:
Extension 'pnp.polacode' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by rasouza** [comment]
Yeah.. can you please update the ext? It's an awesome one

**Comment by JohnzBallad** [comment]
I think polacodes's contributors are not going to pay attention.Last commit was 2 years ago.

**Comment by ghaiklor** [comment]
> I think polacodes' contributors are not going to pay attention. The last commit was 2 years ago.

I see that work is in progress, look not into the `master` branch, but into `rewrite` branch - https://github.com/octref/polacode/commits/rewrite

There are commits on Mar 27, 2019, which are have updated dependencies and some work related to new API.

@octref crossing fingers and waiting for an update.
