### ISSUE TITLE
⚠️ Usage of deprecated API

### ISSUE THREAD

**Issue by sidbentifraouine** [octref/polacode#98]
Hi,
Here is the message: https://cl.ly/be9981edd34d,

Great extension! ❤️

**Comment by Devin97** [comment]
Hope this gets fixed soon, can't wait to use it. Awesome extension!!

**Comment by Toxblh** [comment]
I fixed marketplace.visualstudio.com/items?itemName=Toxblh.polacode-fork

**Comment by Devin97** [comment]
It's working! Thanks @Toxblh 👍
